# -*- coding: utf-8 -*-
"""ejercicio_066.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJFxGoRO7-qZan3WSiIrJwIXM4L52Bhw

# Ejercicio 066 - Sistema de Educacion
    
## Instrucciones
Implementa la clase `EstudianteCursoV7` respetando los siguientes requerimientos:

1. **`__init__(self, nombre: str, promedio: float)`**:
   - Inicializa las variables de instancia: `nombre` (str), `promedio` (float), `calificaciones` (list vacía) y `activo` (bool = True).

2. **`evaluar_condicion(self, limite: float, factor: float) -> float`**:
   - Usa operadores aritméticos, lógicos y condicionales (`if / elif / else`).
   - Si `promedio` >= limite y `activo` es True: retorna `promedio` * factor.
   - Elif `promedio` < limite y `promedio` > 0: retorna `promedio` + 10.0.
   - Else: retorna 0.0.

3. **`procesar_registros(self, datos: list) -> float`**:
   - Usa un ciclo `for` para recorrer `datos` (lista de floats/ints/None).
   - Ignora los elementos que sean `None`.
   - Acumula los valores válidos en `promedio` y agrega cada valor a `calificaciones`.
   - Si `promedio` supera los 500.0, desactiva la entidad (`activo = False`).
   - Retorna el valor final de `promedio`.

4. **`acumular_hasta_objetivo(self, objetivo: float, paso: float) -> int`**:
   - Usa un ciclo `while` para incrementar `promedio` en `paso` mientras `promedio` sea estrictamente menor que `objetivo`.
   - Retorna la cantidad de iteraciones/pasos realizados.
"""

# Escribe tu solución aquí
class EstudianteCursoV7:
    def __init__(self, nombre: str, promedio: float):
        self.nombre = 'nombre'
        self.promedio = promedio
        self.calificaciones = []
        self.activo = True

    def evaluar_condicion(self, limite: float, factor: float) -> float:
        if self.promedio >= limite and self.activo:
            return self.promedio * factor
        elif self.promedio < limite and self.promedio > 0:
            return self.promedio + 10.0
        else:
            return 0.0

    def procesar_registros(self, datos: list) -> float:
        for dato in datos:
            if isinstance(dato, (int, float)) and not isinstance(dato, bool):
                self.promedio += dato
                self.calificaciones.append(dato)

                if self.promedio > 500.0:
                    self.activo = False

        return self.promedio

    def acumular_hasta_objetivo(self, objetivo: float, paso: float) -> int:
        iteraciones = 0
        while self.promedio < objetivo:
            self.promedio += paso
            iteraciones += 1
        return iteraciones

# ==============================================================================
# MOTOR DE AUTOEVALUACIÓN (NO MODIFICAR ESTA CELDA)
# ==============================================================================
import unittest

class TestEjercicio(unittest.TestCase):
    def test_01_init_y_atributos(self):
        obj = EstudianteCursoV7("Test", 50.0)
        self.assertTrue(hasattr(obj, 'nombre'), "Falta el atributo 'nombre'.")
        self.assertTrue(hasattr(obj, 'promedio'), "Falta el atributo 'promedio'.")
        self.assertTrue(hasattr(obj, 'calificaciones'), "Falta el atributo 'calificaciones'.")
        self.assertTrue(hasattr(obj, 'activo'), "Falta el atributo 'activo'.")
        self.assertEqual(getattr(obj, 'activo'), True, "El atributo 'activo' debe ser True por defecto.")

    def test_02_evaluar_condicion(self):
        obj = EstudianteCursoV7("Test", 100.0)
        res1 = obj.evaluar_condicion(50.0, 1.5)
        self.assertEqual(res1, 150.0, "Fallo en la lógica del condicional/multiplicación.")

        obj2 = EstudianteCursoV7("Test2", 20.0)
        res2 = obj2.evaluar_condicion(50.0, 1.5)
        self.assertEqual(res2, 30.0, "Fallo en la rama elif de evaluar_condicion.")

    def test_03_ciclo_for_y_colecciones(self):
        obj = EstudianteCursoV7("Test", 10.0)
        res = obj.procesar_registros([5.0, None, 15.0, 20.0])
        self.assertEqual(res, 50.0, "Fallo en acumulación del ciclo for o filtrado de None.")
        self.assertEqual(len(getattr(obj, 'calificaciones')), 3, "No se ignoraron correctamente los valores None.")

    def test_04_ciclo_while(self):
        obj = EstudianteCursoV7("Test", 10.0)
        pasos = obj.acumular_hasta_objetivo(30.0, 5.0)
        self.assertEqual(pasos, 4, "Fallo en la cantidad de iteraciones del ciclo while.")
        self.assertEqual(getattr(obj, 'promedio'), 30.0, "Fallo en el incremento dentro del ciclo while.")

suite = unittest.TestLoader().loadTestsFromTestCase(TestEjercicio)
runner = unittest.TextTestRunner(verbosity=0)
res = runner.run(suite)

total = res.testsRun
errores = len(res.failures) + len(res.errors)
nota = round(((total - errores) / total) * 10, 1)

print("\n" + "="*45)
print(f" RESULTADO FINAL DE EVALUACIÓN")
print("="*45)
print(f" NOTA OBTENIDA: {nota} / 10.0\n")

if errores > 0:
    print("DETALLE DE DETECCIONES DE ERROR:")
    for f in res.failures:
        print(f" ❌ {f[1]}")
    for e in res.errors:
        print(f" ⚠️ Error de ejecución: {e[1]}")
else:
    print(" 🎉 ¡Excelente! Lógica de POO, ciclos y condicionales correcta.")